<a href="https://colab.research.google.com/github/leehyunggeunkeun/pytorch-study/blob/master/Edwith/1_Basic_ML.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#edwith 부스트코스 파이토치 강의를 보면서 필사하고 느낀점 및 방법들을 까먹지 않게 정리함...
#출처 edwith 부스트 코스 pytorch 강의

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

#데이터셋을 만들고 데이터를 로더하는데 이용
from torch.utils.data import Dataset
from torch.utils.data import DataLoader

In [0]:
x=torch.FloatTensor([[1,2],[3,4]])
y=torch.FloatTensor([[5,6],[7,8]])

In [4]:
torch.cat([x,y],dim=0), torch.cat([x,y],dim=1)

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.],
         [7., 8.]]), tensor([[1., 2., 5., 6.],
         [3., 4., 7., 8.]]))

In [5]:
print(torch.ones_like(x)) 
print(torch.zeros_like(x))

tensor([[1., 1.],
        [1., 1.]])
tensor([[0., 0.],
        [0., 0.]])


In [0]:
x_train=torch.FloatTensor([[1],[2],[3]])
y_train=torch.FloatTensor([[2],[4],[6]])

In [0]:
w=torch.zeros(1,requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [0]:
optimizer=optim.SGD([w,b],lr=0.01)

In [0]:
nb_epochs=1000
for epoch in range(1,nb_epochs+1):
    hypothesis=x_train.matmul(w)+b
    cost=torch.mean((hypothesis-y_train)**2)

    #항상 붙어다니는 3개

    optimizer.zero_grad()   #gradient 초기화
    cost.backward()         #gradient 계산
    optimizer.step()        #개선

간단한 다중회귀 예제

In [0]:
x_train=torch.FloatTensor([[73,80,75],
                           [93,88,93],
                           [89,91,90],
                           [96,98,100],
                           [73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])

In [11]:
w = torch.zeros((3, 1), requires_grad=True)
b = torch.zeros(1, requires_grad=True)
# optimizer 설정
optimizer = optim.SGD([w, b], lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs + 1):
    
    # H(x) 계산
    hypothesis = x_train.matmul(w) + b # or .mm or @

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, nb_epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch    1/20 hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch    2/20 hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch    3/20 hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch    4/20 hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch    5/20 hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371071
Epoch    6/20 hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch    7/20 hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch    8/20 hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch    9/20 hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.493121
Epoch   10/20 hypo

실제 사용되는 일반적인 예제

In [0]:
class LinearRegressionModel(nn.Module):  #선형회귀 클래스 만들기
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1)

    def forward(self, x):
        return self.linear(x)

In [0]:
class MultivariateLinearRegressionModel(nn.Module):  #다중선형회귀 클래스 만들기
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [14]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])
# 모델 초기화
model = MultivariateLinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    # cost 계산
    cost = F.mse_loss(prediction, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()
    
    # 20번마다 로그 출력
    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
    ))

Epoch    0/20 Cost: 60050.960938
Epoch    1/20 Cost: 18825.099609
Epoch    2/20 Cost: 5902.977539
Epoch    3/20 Cost: 1852.578857
Epoch    4/20 Cost: 582.992310
Epoch    5/20 Cost: 185.043091
Epoch    6/20 Cost: 60.306183
Epoch    7/20 Cost: 21.206503
Epoch    8/20 Cost: 8.949690
Epoch    9/20 Cost: 5.106713
Epoch   10/20 Cost: 3.900951
Epoch   11/20 Cost: 3.521895
Epoch   12/20 Cost: 3.401890
Epoch   13/20 Cost: 3.363150
Epoch   14/20 Cost: 3.349870
Epoch   15/20 Cost: 3.344558
Epoch   16/20 Cost: 3.341729
Epoch   17/20 Cost: 3.339708
Epoch   18/20 Cost: 3.337922
Epoch   19/20 Cost: 3.336215
Epoch   20/20 Cost: 3.334541


In [0]:
class CustomDataset():
    def __init__(self):
        self.x_data=        [[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]]
        self.y_data =[[152], [185], [180], [196], [142]]


    def __len__(self):                          #__len__() 데이터셋의 총 데이터수
        return len(self.x_data)

    def __getitem__(self,idx):                  #__getitem__() 어떠한 인덱스 idx를 받았을때, 그에 상응하는 입출력 데이터 반환
        x=torch.FloatTensor(self.x_data[idx])
        y=torch.FloatTensor(self.y_data[idx])
        return x,y


In [0]:
dataset=CustomDataset()
dataloader=DataLoader(dataset,batch_size=len(dataset))

In [17]:
nb_epochs=20
for epoch in range(nb_epochs+1):
    for batch_idx, samples in enumerate(dataloader):
        x_train,y_train =  samples

        prediction=model(x_train)
        # cost 계산
        cost = F.mse_loss(prediction, y_train)
    
        # cost로 H(x) 개선
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()
    
        # 20번마다 로그 출력
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
        ))

Epoch    0/20 Cost: 3.332879
Epoch    1/20 Cost: 3.331219
Epoch    2/20 Cost: 3.329546
Epoch    3/20 Cost: 3.327886
Epoch    4/20 Cost: 3.326223
Epoch    5/20 Cost: 3.324545
Epoch    6/20 Cost: 3.322882
Epoch    7/20 Cost: 3.321221
Epoch    8/20 Cost: 3.319584
Epoch    9/20 Cost: 3.317912
Epoch   10/20 Cost: 3.316266
Epoch   11/20 Cost: 3.314611
Epoch   12/20 Cost: 3.312946
Epoch   13/20 Cost: 3.311310
Epoch   14/20 Cost: 3.309636
Epoch   15/20 Cost: 3.308004
Epoch   16/20 Cost: 3.306324
Epoch   17/20 Cost: 3.304686
Epoch   18/20 Cost: 3.303048
Epoch   19/20 Cost: 3.301390
Epoch   20/20 Cost: 3.299741


In [0]:
# 데이터
x_train = torch.FloatTensor(x_train)
y_train = torch.FloatTensor(y_train)
# 모델 초기화
model = MultivariateLinearRegressionModel()
# optimizer 설정
optimizer = optim.SGD(model.parameters(), lr=1e-5)

nb_epochs = 20
for epoch in range(nb_epochs+1):
    
    # H(x) 계산
    prediction = model(x_train)
    
    

Logistic Regression

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [20]:
torch.manual_seed(1)

In [0]:
x_data=[[1,2],[2,3],[3,1],[4,3],[5,3],[6,2]]
y_data=[[0],[0],[0],[1],[1],[1]]

x_train=torch.FloatTensor(x_data)
y_train=torch.FloatTensor(y_data)

In [0]:
w=torch.zeros((2,1),requires_grad=True)
b=torch.zeros(1,requires_grad=True)

In [23]:
optimizer=optim.SGD([w,b],lr=1)

nb_epochs=1000
for epoch in range(nb_epochs+1):

    hypothesis=torch.sigmoid(x_train.matmul(w)+b)
    cost=F.binary_cross_entropy(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 0.693147
Epoch  100/1000 Cost: 0.134722
Epoch  200/1000 Cost: 0.080643
Epoch  300/1000 Cost: 0.057900
Epoch  400/1000 Cost: 0.045300
Epoch  500/1000 Cost: 0.037261
Epoch  600/1000 Cost: 0.031673
Epoch  700/1000 Cost: 0.027556
Epoch  800/1000 Cost: 0.024394
Epoch  900/1000 Cost: 0.021888
Epoch 1000/1000 Cost: 0.019852


In [0]:
class BinaryClassifier(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(2,1)  
        self.sigmoid=nn.Sigmoid()

    def forward(self,x):
        return self.sigmoid(self.linear(x))

In [0]:
model=BinaryClassifier()

In [26]:
optimizer=optim.SGD(model.parameters(),lr=1)

nb_epochs=100
for epoch in range(nb_epochs+1):

    hypothesis=model(x_train)
    cost=F.binary_cross_entropy(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 10==0:
       prediction=hypothesis>=torch.FloatTensor([0.5])
       correct_prediction=prediction.float()==y_train
       accuracy=correct_prediction.sum().item()/len(correct_prediction)
       print('Epoch {:4d}/{} Cost: {:.6f} Accuracy{:2.2f}'.format(
        epoch, nb_epochs, cost.item(),accuracy*100
        ))

Epoch    0/100 Cost: 0.539713 Accuracy83.33
Epoch   10/100 Cost: 0.614853 Accuracy66.67
Epoch   20/100 Cost: 0.441875 Accuracy66.67
Epoch   30/100 Cost: 0.373145 Accuracy83.33
Epoch   40/100 Cost: 0.316358 Accuracy83.33
Epoch   50/100 Cost: 0.266094 Accuracy83.33
Epoch   60/100 Cost: 0.220498 Accuracy100.00
Epoch   70/100 Cost: 0.182095 Accuracy100.00
Epoch   80/100 Cost: 0.157299 Accuracy100.00
Epoch   90/100 Cost: 0.144091 Accuracy100.00
Epoch  100/100 Cost: 0.134272 Accuracy100.00


Softmax Classification

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [28]:
torch.manual_seed(1)

In [0]:
x_train=[[1,2,1,1],
         [2,1,3,2],
         [3,1,3,4],
         [4,1,5,5],
         [1,7,5,5],
         [1,2,5,6],
         [1,6,6,6],
         [1,7,7,7]]
y_train=[2,2,2,1,1,1,0,0]

x_train=torch.FloatTensor(x_train)
y_train=torch.LongTensor(y_train)

In [0]:
w=torch.zeros((4,3),requires_grad=True) #sample4 class3
b=torch.zeros(1,requires_grad=True)

In [31]:
optimizer=optim.SGD([w,b],lr=0.1)
nb_epochs=1000
for epoch in range(nb_epochs+1):

    hypothesis=x_train.matmul(w)+b
    cost=F.cross_entropy(hypothesis,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100==0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 1.098612
Epoch  100/1000 Cost: 0.761050
Epoch  200/1000 Cost: 0.689991
Epoch  300/1000 Cost: 0.643229
Epoch  400/1000 Cost: 0.604117
Epoch  500/1000 Cost: 0.568255
Epoch  600/1000 Cost: 0.533922
Epoch  700/1000 Cost: 0.500291
Epoch  800/1000 Cost: 0.466908
Epoch  900/1000 Cost: 0.433506
Epoch 1000/1000 Cost: 0.399962


In [0]:
class SoftmaxClassifierModel(nn.Module):
    def  __init__(self):
        super().__init__()
        self.linear=nn.Linear(4,3)

    def forward(self,x):
        return self.linear(x)

In [0]:
model= SoftmaxClassifierModel()

In [34]:
optimizer=optim.SGD(model.parameters(),lr=0.1)

nb_epochs=1000
for epoch in range(nb_epochs+1):

    prediction=model(x_train)
    cost=F.cross_entropy(prediction,y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch % 100==0:
      
       print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, nb_epochs, cost.item()
        ))

Epoch    0/1000 Cost: 1.616785
Epoch  100/1000 Cost: 0.658891
Epoch  200/1000 Cost: 0.573443
Epoch  300/1000 Cost: 0.518151
Epoch  400/1000 Cost: 0.473265
Epoch  500/1000 Cost: 0.433516
Epoch  600/1000 Cost: 0.396563
Epoch  700/1000 Cost: 0.360914
Epoch  800/1000 Cost: 0.325392
Epoch  900/1000 Cost: 0.289178
Epoch 1000/1000 Cost: 0.254148


Tips

In [0]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [36]:
torch.manual_seed(1)

In [0]:
x_train=torch.FloatTensor([[1,2,1],                     #행이 많다고 가정하면  (m ,3)
                           [1,3,2],
                           [1,3,4],
                           [1,5,5],
                           [1,7,5],
                           [1,2,5],
                           [1,6,6],
                           [1,7,7]])
y_train=torch.LongTensor([2,2,2,1,1,1,0,0])            #(m,)

In [0]:
x_test=torch.FloatTensor([[2,1,1],[3,1,2],[3,3,4]])     #(m`,3)

y_test=torch.LongTensor([2,2,2])                                        #(m`,)

In [0]:
class SoftmaxClassifierModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear=nn.Linear(3,3)

    def forward(self,x):
        return self.linear(x)

    

In [0]:
model=SoftmaxClassifierModel()

In [0]:
optimizer=optim.SGD(model.parameters(),lr=0.1)

In [0]:
def train(model, optimizer, x_train, y_train):
    nb_epochs = 20
    for epoch in range(nb_epochs):

        # H(x) 계산
        prediction = model(x_train)

        # cost 계산
        cost = F.cross_entropy(prediction, y_train)

        # cost로 H(x) 개선
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))

In [0]:
def test(model, optimizer, x_test, y_test):
    prediction = model(x_test)
    predicted_classes = prediction.max(1)[1]
    correct_count = (predicted_classes == y_test).sum().item()
    cost = F.cross_entropy(prediction, y_test)

    print('Accuracy: {}% Cost: {:.6f}'.format(
         correct_count / len(y_test) * 100, cost.item()
    ))

In [44]:
train(model, optimizer, x_train, y_train)

Epoch    0/20 Cost: 2.203667
Epoch    1/20 Cost: 1.199645
Epoch    2/20 Cost: 1.142985
Epoch    3/20 Cost: 1.117769
Epoch    4/20 Cost: 1.100901
Epoch    5/20 Cost: 1.089523
Epoch    6/20 Cost: 1.079872
Epoch    7/20 Cost: 1.071320
Epoch    8/20 Cost: 1.063325
Epoch    9/20 Cost: 1.055720
Epoch   10/20 Cost: 1.048378
Epoch   11/20 Cost: 1.041245
Epoch   12/20 Cost: 1.034285
Epoch   13/20 Cost: 1.027478
Epoch   14/20 Cost: 1.020813
Epoch   15/20 Cost: 1.014279
Epoch   16/20 Cost: 1.007872
Epoch   17/20 Cost: 1.001586
Epoch   18/20 Cost: 0.995419
Epoch   19/20 Cost: 0.989365


In [45]:
test(model, optimizer, x_test, y_test)      #overfitting 따라서  lr을 줄여보자!

Accuracy: 0.0% Cost: 1.425844


In [0]:
model=SoftmaxClassifierModel()

In [0]:
optimizer=optim.SGD(model.parameters(),lr=1e-5)

In [48]:
train(model, optimizer, x_train, y_train)

Epoch    0/20 Cost: 1.280268
Epoch    1/20 Cost: 1.280221
Epoch    2/20 Cost: 1.280174
Epoch    3/20 Cost: 1.280128
Epoch    4/20 Cost: 1.280081
Epoch    5/20 Cost: 1.280034
Epoch    6/20 Cost: 1.279988
Epoch    7/20 Cost: 1.279941
Epoch    8/20 Cost: 1.279894
Epoch    9/20 Cost: 1.279848
Epoch   10/20 Cost: 1.279801
Epoch   11/20 Cost: 1.279754
Epoch   12/20 Cost: 1.279708
Epoch   13/20 Cost: 1.279661
Epoch   14/20 Cost: 1.279614
Epoch   15/20 Cost: 1.279568
Epoch   16/20 Cost: 1.279521
Epoch   17/20 Cost: 1.279474
Epoch   18/20 Cost: 1.279428
Epoch   19/20 Cost: 1.279381


In [49]:
test(model, optimizer, x_test, y_test)     

Accuracy: 100.0% Cost: 0.528334


Data Preprocessing

In [0]:
#linear regression

x_train=torch.FloatTensor([[73,80,75],
                           [93,88,93],
                           [89,91,90],
                           [96,98,100],
                           [73,66,70]])
y_train=torch.FloatTensor([[152],[185],[180],[196],[142]])

In [51]:
mu = x_train.mean(dim=0)
sigma = x_train.std(dim=0)
norm_x_train = (x_train - mu) / sigma
norm_x_train

tensor([[-1.0674, -0.3758, -0.8398],
        [ 0.7418,  0.2778,  0.5863],
        [ 0.3799,  0.5229,  0.3486],
        [ 1.0132,  1.0948,  1.1409],
        [-1.0674, -1.5197, -1.2360]])

In [0]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1)

    def forward(self, x):
        return self.linear(x)

In [0]:
model = MultivariateLinearRegressionModel()


In [0]:
def train(model, optimizer, x_train, y_train):
    nb_epochs = 20
    for epoch in range(nb_epochs):

        # H(x) 계산
        prediction = model(x_train)

        # cost 계산
        cost = F.mse_loss(prediction, y_train)

        # cost로 H(x) 개선
        optimizer.zero_grad()
        cost.backward()
        optimizer.step()

        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
            epoch, nb_epochs, cost.item()
        ))


In [55]:
train(model, optimizer, norm_x_train, y_train)


Epoch    0/20 Cost: 29547.708984
Epoch    1/20 Cost: 29547.708984
Epoch    2/20 Cost: 29547.708984
Epoch    3/20 Cost: 29547.708984
Epoch    4/20 Cost: 29547.708984
Epoch    5/20 Cost: 29547.708984
Epoch    6/20 Cost: 29547.708984
Epoch    7/20 Cost: 29547.708984
Epoch    8/20 Cost: 29547.708984
Epoch    9/20 Cost: 29547.708984
Epoch   10/20 Cost: 29547.708984
Epoch   11/20 Cost: 29547.708984
Epoch   12/20 Cost: 29547.708984
Epoch   13/20 Cost: 29547.708984
Epoch   14/20 Cost: 29547.708984
Epoch   15/20 Cost: 29547.708984
Epoch   16/20 Cost: 29547.708984
Epoch   17/20 Cost: 29547.708984
Epoch   18/20 Cost: 29547.708984
Epoch   19/20 Cost: 29547.708984
